global:
  scrape_interval: 60s
  scrape_timeout: 5s
  evaluation_interval: 30s
rule_files:
  # The rules/alerts you want to use/test
  # sometimes this is called alerts.yaml, gatewayAlerts.yml, serviceAlerts.yml etc...
  - rules.yml
  - alerts-mesh-team.yml
  - alerts-genai.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
      scheme: http
      timeout: 20s
      api_version: v2
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: pingpong
    static_configs:
      - targets: ["pingpong:8090"]
  - job_name: envoy
    metrics_path: /stats/prometheus
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["frontend-proxy:10000"]
